
-- Insert UI Components & Kits resources into the existing category
WITH ui_components_category AS (
  SELECT id FROM categories WHERE slug = 'ui-components-kits'
)
INSERT INTO public.resources (title, description, url, category_id, featured) 
SELECT 
  title,
  description,
  url,
  (SELECT id FROM ui_components_category),
  featured
FROM (VALUES
  ('CSSnippets', 'Explore a vast collection of HTML, React, CSS and Tailwind CSS code snippets for buttons, box-shadows, cards, checkboxes, dropdowns and many more', 'https://cssnippets.shefali.dev', false),
  ('Bit', 'Provides a huge library of reuseable UI Components for React, Angular, Vue, React Native. Also can be used for sharing UI Components among other team members', 'https://bit.dev/components', true),
  ('UILang', 'A minimal, UI-focused programming language for web designers', 'http://uilang.com/', false),
  ('Medialoot CSS Components', 'Calendars, price grids and other UI components', 'https://medialoot.com/free-themes/css-components/', false),
  ('Froala Design Blocks', 'Over 170 responsive design blocks ready to be used in your web or mobile apps', 'https://froala.com/design-blocks', false),
  ('Flowbite', 'Open-source library of Tailwind CSS components', 'https://flowbite.com', true),
  ('daisyUI', 'Tailwind CSS Components', 'https://daisyui.com/', true),
  ('Mui Treasury', 'An open-source project that provides a collection of ready-to-use components based on Material-UI', 'https://mui-treasury.com', false),
  ('Material Design For Bootstrap', 'Open source toolkit for building material design with Bootstrap', 'https://mdbootstrap.com/', true),
  ('Photonkit', 'Desktop UI library for Electron', 'http://photonkit.com/', false),
  ('Flat UI', 'Minimal free user interface kit', 'https://designmodo.github.io/Flat-UI/', false),
  ('Shards', 'A free and modern UI toolkit for web makers based on Bootstrap', 'https://designrevision.com/downloads/shards/', false),
  ('Themesberg', 'Free and open-source website themes, templates, and UI kits based on Bootstrap and React', 'https://themesberg.com/templates/free', false),
  ('Creative Tim', 'All types of UI libraries and kits including JS frameworks like React', 'https://www.creative-tim.com/', true),
  ('Brumm Shadow Maker', 'An online tool to make css shadows', 'https://brumm.af/shadows', false),
  ('AdminLTE', 'Best open source admin dashboard & control panel theme', 'https://adminlte.io/', true),
  ('SpinKit', 'Simple CSS Spinners', 'https://tobiasahlin.com/spinkit/', false),
  ('Epic Spinners', 'CSS spinners collection with Vue.js integration', 'https://epic-spinners.epicmax.co/', false),
  ('Loading.io', 'Online service provider for creating simple animations, spinners, progress bar and more', 'https://loading.io/', false),
  ('Moving Letters', 'Animated Text with JavaScript and anime.js', 'https://tobiasahlin.com/moving-letters/', false),
  ('CSS Layout', 'A collection of popular web layouts and patterns in pure CSS', 'https://csslayout.io/', false),
  ('CSS Grid Generator', 'An open-source project that allow users to quickly create dynamic layout based on CSS Grid', 'https://cssgrid-generator.netlify.app/', false),
  ('HTML Table Generator', 'Create semantic, responsive & accessible HTML tables to represent your tabular data. Set CSS properties, generate the code and copy & paste into your project', 'https://www.htmltables.io/', false),
  ('Codyhouse', 'Kick-start your web projects with CodyHouse''s front-end framework and library of accessible HTML, CSS, JavaScript components', 'https://codyhouse.co/', false),
  ('Tailwind Starter Kit', 'Tailwind Starter Kit a beautiful extension for TailwindCSS, Free and Open Source', 'https://github.com/creativetimofficial/tailwind-starter-kit', false),
  ('Tailwindtoolbox', 'Open source starter templates and components, a plugins directory and useful tools/utilities to kick start your Tailwind CSS project', 'https://www.tailwindtoolbox.com/', false),
  ('tailwindcomponents', 'A free repository for community components using TailwindCSS', 'https://tailwindcomponents.com/', true),
  ('sweetalert', 'SweetAlert makes popup messages easy and pretty', 'https://sweetalert.js.org/', false),
  ('sweetalert2', 'A beautiful, responsive, customizable, accessible replacement for javascript''s popup boxes', 'https://sweetalert2.github.io/', true),
  ('tailblocks', 'Open source ready-to-use Tailwind CSS components', 'https://mertjf.github.io/tailblocks/', false),
  ('Fast', 'An interface system that can be used with modern Web Frameworks such as React, Vue and Angular', 'https://www.fast.design/', false),
  ('LottieFiles', 'Interactive animations in many formats like json,gif and mp4, libraries and plugins for Web & Mobile', 'https://lottiefiles.com/', true),
  ('Kutty', 'A set of accessible and reusable prebuilt Tailwind components that are commonly used in web applications', 'https://kutty.netlify.app/', false),
  ('Tailwind Templates', 'A free collection of Tailwindcss Templates - tailwind components for rapid UI development', 'https://tailwindtemplates.io/', false),
  ('Stitches (HTML Generator)', 'An HTML template generator using functional css', 'https://stitches.hyperyolo.com/', false),
  ('Meraki UI Components', 'Beautiful Tailwindcss components that support RTL languages & fully responsive based on Flexbox & CSS Grid', 'https://merakiui.com/', false),
  ('Daemonites Material Design For Bootstrap', 'Daemonite''s Material UI is a cross-platform and fully responsive front-end interface based on Google Material Design developed using Bootstrap 4', 'http://daemonite.github.io/material/', false),
  ('Stitches (CSS-in-JS)', 'CSS-in-JS with near-zero runtime, SSR, multi-variant support, and a best-in-class developer experience', 'https://stitches.dev/', true),
  ('Headless UI', 'Completely unstyled, fully accessible UI components, designed to integrate beautifully with Tailwind CSS', 'https://headlessui.dev/', true),
  ('Styled components', 'Build beautifully UI Components, for your applications & websites', 'https://styled-components.com/', true),
  ('Figma Bootstrap 5 UI Kit', 'UI Kit comprising 300+ organized Bootstrap 5 components built with atomic design system & auto layout', 'https://drive.google.com/file/d/1SZOTxXYfCMujqP2P684Vd5QIrlk5bwe6/view?usp=sharing', false),
  ('Notiflix', 'JavaScript library for client-side non-blocking notifications, popup boxes, loading indicators, and more that makes your web projects much better', 'https://notiflix.github.io', false),
  ('CoreUI', 'Bootstrap Admin Dashboard Template & UI Components Library', 'https://coreui.io', false),
  ('AgnosticUI', 'Accessible React component primitives that also work with Vue 3, Svelte, and Angular', 'https://www.agnosticui.com/', false),
  ('SVGR', 'SVGR is an universal tool to transform a raw SVG into a ready-to-use React components. Available online, in CLI, Node.js, as a webpack/rollup/parcel plugin', 'https://react-svgr.com/', false),
  ('uiverse', 'Hundreds Open-Source UI elements, made with HTML & CSS. Anyone can contribute. Includes buttons, checkboxes, spinners, cards, inputs and more', 'https://uiverse.io', true),
  ('HyperUI', 'Free open source Tailwind CSS components for marketing and ecommerce websites, as well as application UI', 'https://www.hyperui.dev/', true),
  ('Flowbite Admin Dashboard', 'Free and open-source admin dashboard template built with Tailwind CSS and Flowbite featuring 15 examples pages, charts, widgets, and dark mode', 'https://github.com/themesberg/flowbite-admin-dashboard', false),
  ('Wicked Blocks', 'A free collection of Tailwind blocks & components', 'https://wickedblocks.dev/', false),
  ('Mamba UI', 'Mamba UI is a free, open-source collection of UI components and templates based on Tailwind CSS', 'https://mambaui.com/', false),
  ('Kitwind', 'Fully responsive UI kits, built with Tailwind CSS', 'https://kitwind.io/products/kometa/components', false),
  ('DevUI', 'Free and Open-Source UI Components for Maximum Productivity', 'https://www.devui.io/', false),
  ('Tail-Kit', 'Tail-kit gives you access to over 250 free components and free templates, based on Tailwind CSS 3.0', 'https://www.tailwind-kit.com/', false),
  ('Float UI', 'Free and open-source UI components and website templates using Tailwind CSS', 'https://floatui.com/', false),
  ('Konsta UI', 'Pixel perfect mobile UI components built with Tailwind CSS', 'https://konstaui.com/', false),
  ('React Native Gifted Chat', 'A chat UI component that offers a ready-to-use chat interface with features like message bubbles, input toolbar, and more', 'https://github.com/FaridSafi/react-native-gifted-chat#readme', false),
  ('Wind UI', 'Expertly made, responsive, accessible components in React and HTML ready to be used on your website or app', 'https://wind-ui.com/', false),
  ('Sonner', 'An opinionated toast component for React', 'https://sonner.emilkowal.ski/', false),
  ('Pines', 'Pines is a library of animations, sliders, tooltips, accordions, modals, and more! It''s a set of UI elements that can be copy and pasted into any Alpine and Tailwind projects', 'https://devdojo.com/pines', false),
  ('Kuma UI', 'With Kuma UI''s headless, zero-runtime UI components, build top-performing websites effortlessly, while enjoying the best developer experience. Say hello to the future of CSS-in-JS', 'https://www.kuma-ui.com/', false),
  ('Preline UI', 'Preline UI is an open-source set of prebuilt UI components based on the utility-first Tailwind CSS framework', 'https://preline.co/index.html', false),
  ('Flyon UI', 'The Easiest Components Library For Tailwind CSS', 'https://flyonui.com/', false),
  ('Shadcnui Blocks', 'Effortless Shadcn UI Component Previews & Code Snippets', 'https://www.shadcnui-blocks.com/', false)
) AS t(title, description, url, featured)
WHERE NOT EXISTS (
  SELECT 1 FROM resources WHERE title = t.title
);
