
-- Insert CSS framework resources into the existing CSS Frameworks category
WITH frameworks_category AS (
  SELECT id FROM categories WHERE slug = 'css-frameworks'
)
INSERT INTO public.resources (title, description, url, category_id, featured) 
SELECT 
  title,
  description,
  url,
  (SELECT id FROM frameworks_category),
  featured
FROM (VALUES
  ('Tailwind CSS', 'Low level, utility-first framework', 'https://tailwindcss.com/', true),
  ('Bootstrap', 'Popular UI framework with tons of components that use both CSS and JS', 'https://getbootstrap.com/', true),
  ('Materialize', 'A modern responsive front-end framework based on Material Design', 'https://materializecss.com/', true),
  ('Material Design Lite', 'Light framework based on Material Design. No JS dependency', 'https://getmdl.io/', false),
  ('Bulma', 'Modern CSS framework with no JS', 'https://bulma.io/', true),
  ('Skeleton', 'Extremely light framework for basic UI elements', 'http://getskeleton.com/', false),
  ('Uniform CSS', 'Fully configurable utility generator and CSS framework built entirely in Sass', 'https://uniformcss.com/', false),
  ('Semantic UI', 'Empowers designers and developers by creating a shared vocabulary for UI', 'https://semantic-ui.com/', true),
  ('Fomantic UI', 'A community fork of Semantic-UI', 'https://fomantic-ui.com/', false),
  ('Foundation', 'Mobile first framework with clean markup', 'https://get.foundation/', true),
  ('Pure CSS', 'A set of small, responsive CSS modules', 'https://purecss.io/', false),
  ('UIKit', 'Lightweight and modular front-end framework', 'https://getuikit.com/', false),
  ('Susy', 'Lightweight, grid-layout engine for Sass', 'https://www.oddbird.net/susy/', false),
  ('Milligram.io', 'Minimalist CSS framework', 'https://milligram.io/', false),
  ('Vanilla Framework', 'Simple, extensible CSS framework written in Sass', 'https://vanillaframework.io/', false),
  ('Spectre CSS', 'Lightweight, modern CSS framework', 'https://picturepan2.github.io/spectre/', false),
  ('Picnic CSS', 'Lightweight and beautiful library', 'https://picnicss.com/', false),
  ('Wing', 'A beautiful CSS framework designed for minimalists', 'https://kbrsh.github.io/wing/', false),
  ('Chota', 'A micro (~3kb) CSS framework', 'https://jenil.github.io/chota/', false),
  ('Blueprint CSS', 'A lightweight layout library for building great responsive mobile first UIs that work everywhere', 'https://blueprintcss.dev/', false),
  ('W3.CSS', 'A modern CSS framework with support for desktop, tablet, and mobile design by default. Designed to be independent of jQuery or any other JavaScript library', 'https://www.w3schools.com/w3css/', false),
  ('98.css', 'A design system for building faithful recreations of old UIs', 'https://jdan.github.io/98.css/', false),
  ('NES CSS', 'NES-style CSS Framework', 'https://nostalgic-css.github.io/NES.css/', false),
  ('Shoelace.css', 'Lightweight, forward-thinking CSS library built with future CSS syntax', 'https://www.shoelace.style/', false),
  ('MVP.css', 'A minimalist stylesheet for HTML elements. No class names, no frameworks, just semantic HTML and you''re done', 'https://andybrewer.github.io/mvp/', false),
  ('Blaze.css', 'Open source modular CSS toolkit providing great structure for building websites quickly', 'http://blazecss.com/', false),
  ('Turret CSS', 'Turret CSS is a styles framework for development of responsive websites', 'https://turretcss.com/', false),
  ('Cutestrap', 'A strong, independent CSS Framework', 'https://www.cutestrap.com/', false),
  ('XP.css', 'XP.css is an extension of 98.css. A CSS library for building interfaces that look like old UIs', 'https://botoxparty.github.io/XP.css/', false),
  ('Framework7', 'Framework7 - is a free and open source framework to develop mobile, desktop or web apps with native look and feel', 'https://framework7.io/', false),
  ('Hint.css', 'A pure CSS tooltip library for your lovely websites', 'https://kushagra.dev/lab/hint/', false),
  ('imagehover.io', 'Pure CSS Image Hover Effect Library', 'http://imagehover.io/', false),
  ('mini.css', 'A minimal, responsive, style-agnostic CSS framework', 'https://minicss.org/', false),
  ('Tachyons', 'Create fast loading, highly readable, and 100% responsive interfaces with as little css as possible', 'https://tachyons.io/', false),
  ('Material Bootstrap', 'Material Design with Bootstrap', 'https://fezvrasta.github.io/bootstrap-material-design/', false),
  ('Ivory', 'A modern CSS framework for developing powerful web interfaces faster and easier', 'https://github.com/IVORY-UI/ivory', false),
  ('Halfmoon UI', 'A responsive and lightweight framework, designed for quickly building beautiful dashboards and product pages', 'https://www.gethalfmoon.com/', false),
  ('Metro 4', 'Create your site quickly and effectively with Metro 4. impressive components library built on html, css, javascript', 'https://metroui.org.ua/index.html', false),
  ('css-doodle', 'A web component for drawing patterns with CSS', 'https://css-doodle.com/', false),
  ('latex.css', 'Make your website look like a LaTeX document', 'https://latex.now.sh/', false),
  ('Paper CSS', 'Front-end printing solution', 'https://github.com/cognitom/paper-css', false),
  ('Windi CSS', 'Next generation compiler for Tailwind CSS', 'https://windicss.org/', false),
  ('Cirrus CSS', 'A component and utility centric SCSS framework designed for rapid prototyping', 'https://cirrus-ui.netlify.app/', false),
  ('Gutenberg', 'Modern framework to print the web correctly', 'https://github.com/BafS/Gutenberg', false),
  ('lit', 'World''s smallest responsive fire css framework (395 bytes)', 'https://github.com/ajusa/lit', false),
  ('Arwes', 'Arwes is a web framework to build user interfaces based on futuristic science fiction designs, animations, and sound effects', 'https://github.com/arwes/arwes', false),
  ('Bojler', 'Bojler is an email framework for developing responsive and lightweight email templates that will render correctly across each of the most popular email clients', 'https://bojler.slicejack.com/', false),
  ('Tacit', 'Primitive CSS Framework for dummies, without classes', 'https://github.com/yegor256/tacit', false),
  ('Terminal CSS', 'A modern and minimal CSS framework for terminal lovers', 'https://terminalcss.xyz/', false),
  ('Sakura', 'A minimal classless css framework / theme', 'https://oxal.org/projects/sakura/', false),
  ('PSone', 'PS1 style CSS Framework, inspired by NES.css', 'https://github.com/micah5/PSone.css', false),
  ('Marx', 'Marx is the classless CSS reset to be used in any projects (namely small ones)', 'https://github.com/mblode/marx', false),
  ('Tufte', 'Style your webpage like Edward Tufte''s handouts', 'https://github.com/edwardtufte/tufte-css', false),
  ('Axentix', 'Axentix is an open source Framework based on CSS Grid using HTML, CSS and JS', 'https://useaxentix.com/', false),
  ('Raster Simple Grid System', 'Minimal and straight-forward CSS grid system utilizing descriptive HTML rather than semantic CSS', 'https://rsms.me/raster/', false),
  ('flowrift', 'Flowrift is a library made of beautifully designed Tailwind CSS UI blocks', 'https://flowrift.com/c/banner', false),
  ('twind', 'The smallest, fastest, most feature complete tailwind-in-js solution in existence', 'https://twind.dev/', false),
  ('Pico.css', 'Elegant styles for all natives HTML elements without .classes and dark mode automatically enabled', 'https://picocss.com/', false),
  ('clay.css', 'Extensible and configurable micro CSS util class and SASS mixin for adding claymorphism styles to your components', 'https://github.com/codeAdrian/clay.css', false),
  ('BeerCSS', 'Build Material Design interfaces in record time, without stress for devs 🍻. The first CSS framework that implements Material Design 3', 'https://www.beercss.com', false),
  ('UnoCSS', 'UnoCSS is the instant atomic CSS engine, that is designed to be flexible and extensible. The core is un-opinionated, and all the CSS utilities are provided via presets', 'https://unocss.dev/', false),
  ('Neptune CSS', 'Neptune CSS is a lightweight CSS framework. Use it to develop your websites faster', 'https://neptunecss.org', false),
  ('StyleX', 'StyleX is a simple, easy-to-use JavaScript syntax and compiler for styling web apps', 'https://stylexjs.com/', false),
  ('Orbit', 'Orbit is the first CSS framework for creating simple or complex radial interfaces', 'https://github.com/zumerlab/orbit', false)
) AS t(title, description, url, featured)
WHERE NOT EXISTS (
  SELECT 1 FROM resources WHERE title = t.title
);
