
-- Insert only the color resources into the existing Colors category
WITH colors_category AS (
  SELECT id FROM categories WHERE slug = 'colors'
)
INSERT INTO public.resources (title, description, url, category_id, featured) 
SELECT 
  title,
  description,
  url,
  (SELECT id FROM colors_category),
  featured
FROM (VALUES
  ('Colorlab', 'Create color palette, gradients, color scales, check contrast all in one place', 'https://getcolorlab.com', true),
  ('Color Brewer 2', 'The original color palette generator, also supporting color blindness. Probably the scientifically best option', 'https://colorbrewer2.org/', true),
  ('Huetone', 'A tool to create accessible color systems', 'https://github.com/ardov/huetone', false),
  ('Colormind.io', 'Color palette generator', 'http://colormind.io', false),
  ('ColorCurves.app', 'Color palette generator that uses curves to generate color palettes', 'https://colorcurves.app', false),
  ('ColorGradient', 'A free tool to create simple and complex CSS Gradients visually', 'https://colorgradient.dev/', false),
  ('Coolors', 'Create the perfect palette or get inspired by thousands of beautiful color schemes', 'https://coolors.co', true),
  ('UI Colors', 'Tailwind CSS color palette generator', 'https://uicolors.app/create', true),
  ('HTML Color Codes', 'Get HTML color codes, Hex color codes, RGB and HSL values with our color picker, color chart and HTML color names', 'https://htmlcolorcodes.com/', false),
  ('Colors & Fonts', 'A curated library of colors, fonts and resources', 'https://www.colorsandfonts.com/', false),
  ('Palette List', 'Pick 2 colors you like and the tool generates thousands of palettes for you', 'https://www.palettelist.com/', false),
  ('Google Material Color Tool', 'Official Google Material Color Palette Tool', 'https://material.io/resources/color/', true),
  ('Material Palette', 'Free to pick palettes, icons and colors for Material Design', 'https://www.materialpalette.com/', false),
  ('ColorSpace', 'Generate nice color palettes from one color', 'https://mycolor.space/', false),
  ('FlatUIColors', 'Beautiful set of color palettes in various flavors', 'https://flatuicolors.com', false),
  ('Adobe Color', 'Create color palettes, extract gradients from images, etc', 'https://color.adobe.com/create', true),
  ('Colorsinspo', 'All-in-one resource for finding everything about colors', 'https://colorsinspo.com/', false),
  ('ColorsWall', 'Place to store your color palettes and generate palette in one click', 'https://colorswall.com/', false),
  ('Happyhues', 'Happy Hues is a color palette inspiration site that acts as a real-world example as to how the colors could be used in your design projects by Mackenzie Child', 'https://www.happyhues.co/', false),
  ('Adobe Trends', 'Discover current color trends in different industries from the creative communities on Behance and Adobe Stock', 'https://color.adobe.com/trends', false),
  ('Color Hunt', 'A free and open platform for color inspiration with thousands of trendy hand-picked color palettes', 'https://colorhunt.co/', true),
  ('Gradient Hunt', 'A free and open platform for gradient inspiration with thousands of trendy hand-picked color gradients', 'https://gradienthunt.com/', false),
  ('Web Gradients', 'A free website to find good CSS gradients', 'https://webgradients.com/', false),
  ('ColorBox', 'A free website to produce color set', 'https://www.colorbox.io', false),
  ('CSS gradient', 'A free website to make custom gradient and some examples of gradient', 'https://cssgradient.io/', false),
  ('gradienta', 'A pure css and jpg gradients', 'https://gradienta.io/', false),
  ('UI Gradients', 'UI gradients color generator', 'https://uigradients.com/', false),
  ('Palette Generator', 'Generate new color palette with every spacebar press', 'https://palettegenerator.colorion.co/', false),
  ('Material Palettes', '1000+ Material Design palettes', 'https://material.colorion.co/', false),
  ('Grabient', 'Gradient Selector', 'https://www.grabient.com/', false),
  ('ShadeSwash', 'Quickly generate shades of any color', 'https://shadeswash.netlify.app/', false),
  ('BrandColors', 'The biggest collection of official brand color codes', 'http://brandcolors.net/', false),
  ('BRAND PALETTES', 'Logo Color Codes and Palettes', 'https://brandpalettes.com/', false),
  ('Material Design Palette Generator', 'Generate theme and color palette Material Design-like', 'http://mcg.mbitson.com', false),
  ('Colorate', 'Color scheme tool for designers and developers. This will help you draw inspiration and serve as a resource for your color work', 'https://colorate.azurewebsites.net/', false),
  ('0to255', 'A color tool that makes it easy to lighten and darken colors. It''s perfect for hover states, borders, gradients, and more', 'https://www.0to255.com/', false),
  ('Color Blender', 'A tool that shows the midpoint colors between two colors', 'https://meyerweb.com/eric/tools/color-blend', false),
  ('Gradient Buttons', 'Ready to use copy/paste gradient buttons', 'https://gradientbuttons.colorion.co/', false),
  ('Khroma', 'Khroma uses AI to learn which colors you like and creates limitless palettes for you to discover, search, and save', 'http://khroma.co/', false),
  ('whocanuse', 'A tool that brings attention and understanding to how color contrast can affect different people with visual impairments', 'https://whocanuse.com', false),
  ('Colorable', 'Color combination contrast tester', 'https://colorable.jxnblk.com/', false),
  ('Color Hex Picker', 'Tool to get hex code along with name of the color', 'https://colorhexpicker.com', false),
  ('Saruwakakun', 'The stunning color scheme for website & App Designs with previews', 'https://saruwakakun.com/en/color-ideas', false),
  ('Paletton', 'Paletton.com is a designer color tool designed for creating color combinations that work together well', 'https://paletton.com/', false),
  ('Colorzilla', 'A powerful online Photoshop-like CSS gradient editor', 'https://www.colorzilla.com/', false),
  ('CSS Gradient Editor', 'You may only need this tool for creating CSS gradient backgrounds and patterns', 'https://www.cssgradienteditor.com', false),
  ('Image Color Picker', 'Image color picker and palette generator', 'https://image-color.com/', false),
  ('CombineCOLORS', 'Color mixing tool', 'https://combinecolors.com/', false),
  ('Color Lovers', 'It will show the color schemes which are popular in the outside world', 'https://www.colourlovers.com/palettes', false),
  ('HTML CSS Color', 'Free online Color (USA) or Colour (British) tools: information, gradient generator, color wheels etc', 'https://www.htmlcsscolor.com/', false),
  ('HEX Color Codes', 'It gets HTML color codes, Hex color codes, RGB and HSL values with our color picker, color chart and HTML color names', 'https://hexcolorcodes.org/', false),
  ('CoolHue 2.0', 'A free tool that shows different gradient examples in CSS and PNG format', 'https://webkul.github.io/coolhue/', false),
  ('Colors.lol', 'Interesting color palettes generated by a Twitter bot, there are hex codes and descriptive names for each color', 'https://colors.lol/', false),
  ('colors.dopely', 'Super-fast and simple color palette generator, palettes can be saved and shared in seconds', 'https://colors.dopely.top/', false),
  ('UIColor Picker', 'A collection of UI Colors with hex codes available to be copied in just one click', 'https://uicolorpicker.com/', false),
  ('Color Hex', 'Color-hex gives information about colors including color models (RGB,HSL,HSV and CMYK) and generates a simple css code for the selected color', 'https://www.color-hex.com', false),
  ('FarbVelo', 'A random color palette generator', 'https://farbvelo.elastiq.ch/', false),
  ('Veranda Color', 'Browse color palettes made by other designers, generate and submit your own', 'https://verandacolor.com', false),
  ('Duo', 'Duo is a collection of colour combinations that I''ve curated from personal projects or that I''ve come across on the web', 'https://duo.alexpate.uk/', false),
  ('Lospec Palette List', 'The Lospec Palette List is a database of palettes for pixel art', 'https://lospec.com/palette-list', false),
  ('Palettte App', 'Build smooth color schemes that flow from one color to another', 'https://palettte.app', false),
  ('Eggradients', 'Gradient Background Colors with eggs', 'https://www.eggradients.com/', false),
  ('Gradientos', 'Find and test gradients easily', 'https://www.gradientos.app/', false),
  ('Encycolorpedia', 'Website for referencing web colors. Color knowledge, Web colors, Hex color codes', 'https://encycolorpedia.com/', false),
  ('Croma', 'Powerful color tools including an eyedropper, color picker, and palette generator', 'https://chroma.dev/', false),
  ('Color Designer', 'A gradient generetor from one color', 'https://colordesigner.io/gradient-generator', false),
  ('Duotone', 'Find beautiful free duotone images to use in any project, or make custom duotone images by uploading your own image and applying a duotone effect in seconds', 'https://duotone.shapefactory.co/', false),
  ('coolbackgrounds generator', 'Explore a beautifully curated selection of cool backgrounds that you can add to blogs, websites', 'https://coolbackgrounds.io/', false),
  ('Color Shades Generator', 'We can quickly generate color shades of our favorite colors or any colors, to create templates or css components with multiple color shades and more useful tools available on same site', 'https://mdigi.tools/color-shades/', false),
  ('Huemint', 'Huemint uses machine learning to create unique color schemes for your brand, website or graphic', 'https://huemint.com/', false),
  ('InclusiveColors palette creator', 'Create custom accessible Tailwind-style color palettes, where you can modify HSL curves across whole swatches, check WCAG/APCA contrast, then export to Tailwind/CSS/Figma/Adobe', 'https://www.inclusivecolors.com/', false),
  ('AiSeka', 'Discover Created the best Color Palette & Color Tools', 'https://www.aiseka.com/', false)
) AS t(title, description, url, featured)
WHERE NOT EXISTS (
  SELECT 1 FROM resources WHERE title = t.title
);
