
-- Insert React UI Libraries resources into the existing category
WITH react_ui_category AS (
  SELECT id FROM categories WHERE slug = 'react-ui-libraries'
)
INSERT INTO public.resources (title, description, url, category_id, featured) 
SELECT 
  title,
  description,
  url,
  (SELECT id FROM react_ui_category),
  featured
FROM (VALUES
  ('Material UI', 'React components for faster and easier web development, based on Material Design', 'https://material-ui.com/', true),
  ('Chakra UI', 'Build accessible React apps & websites with speed. Openchakra', 'https://chakra-ui.com/', true),
  ('React Bootstrap', 'Bootstrap rebuilt for React. Include Bootstrap components right in your JavaScript', 'https://react-bootstrap.github.io/', true),
  ('Semi Design', 'A modern, comprehensive, flexible design system that gives you all modular blocks you need to build sensible web apps & SaaS products', 'https://semi.design/en-US', false),
  ('Mantine', 'React components and hooks library with native dark theme support focused on usability, accessibility and developer experience', 'https://mantine.dev/', true),
  ('NextUI', 'Beautiful, fast and modern React UI library that allows you to create beatiful websites regardless of your design experience', 'https://nextui.org/', true),
  ('Arco Design', 'A comprehensive React UI components library based on the Arco Design system', 'https://arco.design/en-US', false),
  ('ui-playbook', 'The documented collection of UI components', 'https://uiplaybook.dev/', false),
  ('ReactStrap', 'Another Bootstrap UI library for React', 'https://reactstrap.github.io/', false),
  ('React Admin', 'A frontend Framework for building admin applications. Supports API''s out of the box', 'https://marmelab.com/react-admin/', true),
  ('BlueprintJS', 'React-based UI toolkit for the web', 'https://blueprintjs.com/', false),
  ('React Semantic UI', 'UI components based off of the Semantic UI framework', 'https://react.semantic-ui.com/', false),
  ('Shards React', 'React UI kit featuring a modern design system with dozens of custom components', 'https://designrevision.com/downloads/shards-react/', false),
  ('React Virtualized', 'UI set for data. Includes tables, lists, sorting, etc.', 'https://bvaughn.github.io/react-virtualized', false),
  ('React Toolbox', 'Material design UI library for React', 'http://react-toolbox.io/#/', false),
  ('Elastic UI', 'Distributes UI React components and static assets for use in building web layouts', 'https://elastic.github.io/eui/#/', false),
  ('React Desktop', 'Desktop styled components in React. Includes MacOS and Windows based components', 'http://reactdesktop.js.org/', false),
  ('Theme UI', 'Build consistent, themeable React apps based on constraint-based design principles', 'https://theme-ui.com/home', false),
  ('Onsen React', 'Distributes Components for hybrid mobile apps with React and Onsen UI', 'https://onsen.io/react/', false),
  ('Evergreen', 'Design system for React', 'https://evergreen.segment.com/', false),
  ('Rebass', 'React primitive UI components built with styled system', 'https://github.com/rebassjs/rebass', false),
  ('Grommet', 'mobile first UI component library', 'https://v2.grommet.io/', false),
  ('Landing Page Template', 'Open source landing page template for react', 'https://github.com/cruip/open-react-template/', false),
  ('Elemental UI', 'A UI Toolkit for React.js Websites and Apps', 'http://elemental-ui.com/', false),
  ('Ant Design', 'Open source design React UI library', 'https://ant.design/', true),
  ('Bumbag', 'Bumbag is a friendly React UI Kit suitable for MVPs or large-scale applications', 'https://bumbag.style/', false),
  ('PRIMEREACT', 'The ultimate collection of design-agnostic, flexible and accessible React UI Components', 'https://www.primefaces.org/primereact/', false),
  ('Primer Components', 'Primer Components are React components which implement GitHub''s Primer Design System', 'https://primer.style/components/', false),
  ('Orbit', 'Design system and React UI components for travel projects', 'https://orbit.kiwi/', false),
  ('Base Web', 'Base Web provides a robust suite of components out of the box', 'https://baseweb.design/', false),
  ('Backpack UI', 'Backpack is the Lonely Planet toolset that we use to build front end apps', 'http://lonelyplanet.github.io/backpack-ui/?path=/story/styles--design-tokens', false),
  ('Reaviz', 'Data visualization library for React based on D3', 'https://reaviz.io', false),
  ('React Suite', 'A suite of React components, sensible UI design, and a friendly development experience', 'https://rsuitejs.com/en/', false),
  ('React Spring', 'Spring-physics based animation library for React applications', 'https://www.react-spring.io/', true),
  ('Recharts', 'A composable charting library built on React components', 'http://recharts.org/en-US/', true),
  ('Vercel UI', 'Modern and minimalist React UI library', 'https://github.com/geist-org/react', false),
  ('Framer Motion', 'A React library to power production-ready animations', 'https://www.framer.com/motion/', true),
  ('React Spectrum', 'A React implementation of Spectrum, Adobe''s design system', 'https://react-spectrum.adobe.com/react-spectrum/index.html', false),
  ('@tsparticles/react', 'A lightweight React component for creating particles', 'https://github.com/tsparticles/react', false),
  ('particles-bg', 'A React particles animation background component', 'https://github.com/lindelof/particles-bg', false),
  ('Treact', 'Gallery of free and modern React templates and UI components developed using TailwindCSS as the front-end framework', 'https://treact.owaiskhan.me', false),
  ('OAH-Admin', 'a free React admin dashboard template based on Gatsby with oah-ui components and elements package', 'https://gatsby-admin.paljs.com/extra-components/progress/', false),
  ('Carolina Admin Dashboard', 'Free React admin template is powered by Material-UI components framework and features a clean and fresh design following Google''s Material Design specifications', 'https://demo.uifort.com/carolina-react-admin-dashboard-material-ui-free-demo/LandingPage', false),
  ('Tabler', 'Tabler is a free React admin dashboard template ideal for any kind of back-end web application', 'https://github.com/tabler/tabler-react', false),
  ('Sha-el-design', 'React components for easier customization and smooth development flow', 'https://github.com/sha-el/sha-el-design', false),
  ('React-WeUI', 'React-WeUI made from our love of React and WeChat''s WeUI Design', 'https://weui.github.io/react-weui/docs/#/react-weui/docs/page/0/articles/0', false),
  ('Supabase UI', 'An open-source UI component library inspired by Tailwind and AntDesign', 'https://ui.supabase.io/', false),
  ('Ring UI', 'A collection of JetBrains Web UI components', 'https://github.com/JetBrains/ring-ui', false),
  ('React95', 'Refreshed Windows 95 style UI components for your React app', 'https://react95.io/', false),
  ('Reakit', 'Reakit is a lower level component library for building accessible high level UI libraries, design systems and applications with React', 'https://reakit.io/', false),
  ('Zent', 'A collection of essential UI components written with React', 'https://github.com/youzan/zent', false),
  ('Gestalt', 'A set of React UI components that supports Pinterest''s design language', 'https://github.com/pinterest/gestalt', false),
  ('xstyled', 'A CSS-in-JS framework built for React with props based utilities like display, fontSize or rotate', 'https://xstyled.dev/', false),
  ('@use-gesture', 'Bread n butter utility for component-tied mouse/touch gestures in React', 'https://github.com/pmndrs/use-gesture', false),
  ('React Rainbow', 'React Rainbow is a collection of components that will reliably help you build your application in a snap', 'https://react-rainbow.io/', false),
  ('React Use Smooth Scroll', 'React Provider Component to add a smooth scroll effect', 'https://github.com/saidMounaim/React-Use-Smooth-Scroll', false),
  ('Choc UI', 'Choc UI is a set of accessible and reusable components that are commonly used in web applications', 'https://choc-ui.com/', false),
  ('Elementz', 'A React Component library for buliding modern applications easily & quickly', 'https://elementz.style/', false),
  ('Radix UI', 'Unstyled, accessible components for building high‑quality design systems and web apps in React', 'https://www.radix-ui.com/', true),
  ('Materio MUI React NextJS Admin Template', 'Most Powerful & Comprehensive Open-source MUI React NextJS Admin Dashboard Template built for developers', 'https://github.com/themeselection/materio-mui-react-nextjs-admin-template-free', false),
  ('Chakra Templates', 'A growing collection of hand-crafted & responsive Chakra UI templates ready to drop into your React project', 'https://chakra-templates.dev/', false),
  ('React Resizable Panels', 'React components for resizable panel groups/layouts', 'https://github.com/bvaughn/react-resizable-panels', false),
  ('Carbon React', 'Extensive library of React components for Websites and UI''s. Based on the Carbon Design System from IBM', 'https://carbondesignsystem.com/developing/frameworks/react/', false),
  ('React Aria', 'A library of React Hooks that provides accessible UI primitives for your design system', 'https://react-spectrum.adobe.com/react-aria/', false),
  ('shadcn/ui', 'Beautifully designed components built with Radix UI and Tailwind CSS', 'https://ui.shadcn.com/', true),
  ('Tremor', 'React components to build charts and dashboards with', 'https://tremor.so/', false),
  ('Aceternity UI', 'Copy paste the most trending components and use them in your websites without having to worry about styling and animations', 'https://ui.aceternity.com/', true),
  ('Magic UI', 'free and open-source animated components built with React, Typescript, Tailwind CSS, and Framer Motion', 'https://magicui.design/', false),
  ('Code UI', 'Beautifully designied mobile responsive components built with HTML, CSS , JS and React, Typescript, Tailwind CSS, and Framer Motion. 100% open-source, and customizable', 'https://www.codeui.co.in/', false),
  ('Edil Ozi', 'Component Library for Developers. Open Source components you can copy and paste to your apps', 'https://www.edilozi.pro/', false)
) AS t(title, description, url, featured)
WHERE NOT EXISTS (
  SELECT 1 FROM resources WHERE title = t.title
);
