
-- Insert Others category resources into the existing category
WITH others_category AS (
  SELECT id FROM categories WHERE slug = 'others'
)
INSERT INTO public.resources (title, description, url, category_id, featured) 
SELECT 
  title,
  description,
  url,
  (SELECT id FROM others_category),
  featured
FROM (VALUES
  ('Figpeek', 'Figpeek is a new Figma and GitHub thumbnail generator', 'https://figpeek.vercel.app/', false),
  ('Image Extractor', 'Online tool for extracting all images and SVGs of a website, all you is just to drop the URL', 'https://extract.pics/', true),
  ('Vertopal', 'Free online platform for converting computer files to a variety of file formats', 'https://www.vertopal.com/', true),
  ('everysize.kibalabs.com', 'Check your awesome responsive webpage looks great in every size', 'https://everysize.kibalabs.com/', true),
  ('Devhints.io', 'This is a modest collection of cheatsheets on Internet', 'https://devhints.io/', true),
  ('The Web Toolbox', 'A collection of handy, free-to-use tools for web developers, programmers and designers', 'https://thewebtoolbox.cc/', true),
  ('WebDevTrick', 'A famous blog for many amazing HTML, CSS, JQuery designs', 'https://webdevtrick.com/', false),
  ('css-tricks', 'Free CSS tricks and some unique ideas for beginners and advanced', 'https://css-tricks.com/', true),
  ('Material Design Resources', 'Use Material tools, downloads, and interactive projects to simplify your workflow', 'https://material.io/resources', true),
  ('Nodesign.dev', 'A collection of tools for developers who have little to no artistic talent', 'https://nodesign.dev', true),
  ('A11ygator', 'A web tool to scan websites against WCAG rules', 'https://a11ygator.chialab.io/', false),
  ('Commitizen', 'Command line tool to formatted commit messages according to the standards', 'http://commitizen.github.io/cz-cli/', false),
  ('CleanCss', 'Tool For Code Formatter, Minifier, File Converter', 'https://www.cleancss.com/', false),
  ('Tiny helpers', 'A collection of free single-purpose online tools for web developers', 'https://tiny-helpers.dev/', true),
  ('CSS Ribbon Generator', 'This generator will assist in creating a pure CSS corner ribbon', 'https://www.cssportal.com/css-ribbon-generator/', false),
  ('Can I Use', 'Check cross-browser compatibility of frontend technologies', 'https://caniuse.com/', true),
  ('kangax-js-compat-table', 'Check JavaScript versions (ES5, ES6, ES2016+ etc.) compatibility across different compilers, servers/runtimes and platforms (Desktop and Mobile)', 'https://compat-table.github.io/compat-table/es6/', false),
  ('mydevice.io', 'Most commonly used device resolutions including phones and tablets', 'https://www.mydevice.io/', false),
  ('Codepen', 'Build, test and discover frontend code', 'https://codepen.io/', true),
  ('Responsively', 'A tool for designers and frontend developers to design and debug their in all platforms with ease', 'https://responsively.app', true),
  ('html2pdf.js', 'Client-side HTML-to-PDF rendering using pure JS', 'https://ekoopmans.github.io/html2pdf.js/', false),
  ('CSS Reference', 'A collection of all css properties and definitions in detail', 'https://cssreference.io/', true),
  ('Critical Path CSS Generator', 'Generate critical css for your web pages', 'https://www.sitelocity.com/critical-path-css-generator', false),
  ('SVG Gobbler', 'Browser extension to find SVGs on a webpage and download, copy to clipboard, or export as PNG', 'https://github.com/rossmoody/svg-gobbler', false),
  ('shortcode.dev', 'A collection of useful snippets and code examples for HTML, CSS, JavaScript, Node, Artisan, Blade and more', 'https://shortcode.dev', true),
  ('30secondsofcode.org', 'A wide variety of snippet and article collections for CSS, JavaScript, Python and more', 'https://www.30secondsofcode.org/', true),
  ('PlayCode', 'Javascript playground', 'https://playcode.io/', false),
  ('All The Tags', 'All HTML tags briefly explained', 'https://allthetags.com/', false),
  ('Vue Telemetry', 'Reveal the Vue plugins and technology stack powering any website or explore a database of 5500+ websites', 'https://vuetelemetry.com/', false),
  ('Grid.js', 'Grid.js is a Free and open-source HTML table plugin written in TypeScript. It works with most JavaScript frameworks, including React, Angular, Vue and VanillaJs', 'https://gridjs.io/', false),
  ('Gerillass', 'Gerillass is a website development tool built on top of Sass with a set of Sass mixins and functions for frontend developers to generate scalable CSS outputs', 'https://gerillass.com/', false),
  ('Sketchize', 'Sketchize is built for UI/UX Designers to help them design lovely apps for mobile, tablet, and desktop devices', 'https://www.sketchize.com/', false),
  ('{CSS}Portal', 'CSSPortal is home to a large range of CSS generators, tools and resources', 'https://www.cssportal.com/', false),
  ('DevDocs', 'DevDocs combines multiple API documentations in a fast, organized, and searchable interface', 'https://devdocs.io/', true),
  ('papersizes', 'The best resource for International Paper Sizes, Dimensions & Formats', 'https://papersizes.io/', false),
  ('flexboxfroggy', 'Help Froggy and friends by writing CSS code!', 'http://flexboxfroggy.com/', true),
  ('Designbetter Books', 'Essential reading on the practices that propel the best design teams forward', 'https://www.designbetter.co/books', false),
  ('OverAPI', 'Collection Of All Cheat Sheets', 'https://overapi.com/', true),
  ('Pageclip', 'A server for your Static HTML forms', 'https://pageclip.co/', false),
  ('Shields', 'Create badges with your own customization', 'https://shields.io', false),
  ('williamsharkey', 'Random SVG Graphic Generator', 'http://williamsharkey.com/Shapes.html', false),
  ('Bootstrap CheatSheet', 'An interactive list of Bootstrap classes, variables, and mixins. The only Bootstrap CheatSheet you will ever need', 'https://bootstrap-cheatsheet.themeselection.com/', true),
  ('QR Code Generator', 'Use QR Code Generator to easily create a QR code for your project', 'https://markodenic.com/tools/qr-code-generator/', false),
  ('PapersDB', 'The Biggest Paper Database with Sizes, Dimensions and Formats in Metric and Imperial units', 'https://papersdb.com/', false),
  ('SETools.xyz', 'Free Online tools website for work', 'https://www.setools.xyz/', false),
  ('SmallDev.tools', 'Free tool for developers to help with Beautify & Minify HTML/CSS/Javascript, and many other handy tools. With a delightful interface', 'https://SmallDev.tools/', true),
  ('Angry Tools', 'Free web tools for speed up your development', 'https://angrytools.com/', false),
  ('Rapid API', 'Discover and connect to thousands of APIs', 'https://rapidapi.com/hub', true),
  ('Readme.so', 'The easisest way to create a README', 'https://readme.so', true),
  ('Showcode', 'Beautiful code screenshot generator', 'https://showcode.app', false),
  ('tldraw', 'A tiny little drawing app', 'https://www.tldraw.com', false),
  ('devices.css', 'Pure CSS phones and tablets by Marvel App', 'http://marvelapp.github.io/devices.css/', false),
  ('Troopl', 'Build and publish a free portfolio in minutes', 'https://troopl.com', false),
  ('Apifox', 'Apifox = Postman + Swagger + Mock + JMeter', 'https://apifox.cn', false),
  ('A Modern CSS Reset', 'Resets the css styling of all HTML elements to a consistent baseline across browsers', 'https://piccalil.li/blog/a-modern-css-reset/', false),
  ('Clipperly', 'All-in-one free online file service, convert, edit and optimize your files', 'https://clipperly.com/', false),
  ('DebugBear Speed Test', 'Test and optimize page load speed', 'https://www.debugbear.com/test/website-speed', false),
  ('Code Beautify', 'Free Online Tools like Code Beautifiers, Code Formatters, Editors, Viewers, Minifier, Validators, Converters for Developers', 'https://codebeautify.org/', true),
  ('Vue CheatSheet', 'An interactive cheatsheet of Vue, Vue Router, and Pinia. The only Vue CheatSheet you will ever need', 'https://vue-cheatsheet.themeselection.com/', true),
  ('appydev', 'A collection of awesome tools, resources and products for people who create and live on the internet', 'https://appydev.co/', false),
  ('ExtendsClass', 'Free online tools for developers, including image compressors/encoders, code formatters, code playgrounds, and many other handy utilities', 'https://extendsclass.com/', false),
  ('RunJS', 'Free online JavaScript playground', 'https://runjs.app/play', false),
  ('Pillarstack', 'Assorted resources for frontend developers and web designers', 'https://www.pillarstack.com/', false)
) AS t(title, description, url, featured)
WHERE NOT EXISTS (
  SELECT 1 FROM resources WHERE title = t.title
);
