
-- Add missing categories from the user's list
INSERT INTO public.categories (name, slug) VALUES
('UI Graphics', 'ui-graphics'),
('Fonts', 'fonts'),
('Colors', 'colors'),
('Icons', 'icons'),
('Logos', 'logos'),
('Favicons', 'favicons'),
('Icon Fonts', 'icon-fonts'),
('Stock Photos', 'stock-photos'),
('Stock Videos', 'stock-videos'),
('Stock Music & Sound Effects', 'stock-music-sound-effects'),
('Vectors & Clip Art', 'vectors-clip-art'),
('Product & Image Mockups', 'product-image-mockups'),
('HTML & CSS Templates', 'html-css-templates'),
('CSS Methodologies', 'css-methodologies'),
('CSS Animations', 'css-animations'),
('Javascript Animation Libraries', 'javascript-animation-libraries'),
('Javascript Chart Libraries', 'javascript-chart-libraries'),
('UI Components & Kits', 'ui-components-kits'),
('React UI Libraries', 'react-ui-libraries'),
('Vue UI Libraries', 'vue-ui-libraries'),
('Angular UI Libraries', 'angular-ui-libraries'),
('Svelte UI Libraries', 'svelte-ui-libraries'),
('React Native UI Libraries', 'react-native-ui-libraries'),
('Design Systems & Style Guides', 'design-systems-style-guides'),
('Online Design Tools', 'online-design-tools'),
('Downloadable Design Software', 'downloadable-design-software'),
('Design Inspiration', 'design-inspiration'),
('Image Compression', 'image-compression'),
('Chrome Extensions', 'chrome-extensions'),
('Firefox Extensions', 'firefox-extensions'),
('AI Graphic Design Tools', 'ai-graphic-design-tools'),
('Others', 'others')
ON CONFLICT (name) DO NOTHING;
