// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnvobklibalblbwkmxoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1udm9ia2xpYmFsYmxid2tteG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTIxMjEsImV4cCI6MjA2NjAyODEyMX0.qpb312s3fNAuWpx2_8rQ6z8WcIgUqMKEI7UmvyxU5cg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);